### ISSUE TITLE
Timeouts should not be counted as runner failures

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#10]
Because consistent timeouts can also be caused by significant slowdowns.

**Comment by ejgallego** [comment]
You'd like to grab the build time and if close to 3h don't retry, I'd guess.

**Comment by Zimmi48** [comment]
It might be even simpler than this. GitLab recently implemented a feature request of mine and now the webhooks come with a `build_failure_reason` (https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#build-events). They don't document the possible values but I'd bet than `timeout` is one of them. I'm just lacking time to work on the bot this week because I'm writing a paper but next week, I'll go back to this.

**Comment by Zimmi48** [comment]
Unfortunately, the `build_failure_reason` of GitLab CI is not very reliable so we still have to look at the trace when it says "script_failure" and then we have to make sure the build didn't run for too long otherwise it might just be a timeout. I suppose I should start collecting such examples and report them as bugs to GitLab.
