### ISSUE TITLE
re-run button in "checks" tab does not work

### ISSUE THREAD

**Issue by gares** [coq/bot#113]
In the CI report box one clicks details, and the checks tab is selected. There there is a re-run button, but that does not seem to work. Following "more details on gitlab" and then clicking re-run works.

**Comment by Zimmi48** [comment]
Indeed, thanks for opening the issue. It's on my todo to had support for this button (and possibly other actions from the Checks tab as well).

**Comment by Zimmi48** [comment]
Fixed in 5f39e2770e4a36d64189759ff17757844318eb5b.
