### ISSUE TITLE
[nit] [feature] Add committer name to `coqbot merge` commit messages

### ISSUE THREAD

**Issue by ejgallego** [coq/bot#139]
Dear coqbot devs,

it would be great if the name of the developer doing the merge could appear in the coqbot commit message when we do `coqbot merge`; unless I am mistaken it seems to me this information is missing, and IMHO it is important for several purposes.

**Comment by Zimmi48** [comment]
I agree. This was discussed before and I was interested in hearing suggestions on what git tag to use for this.

BTW, a related question is: should we keep using GitHub nicknames when merging with the bot or should we switch to using `Fullname <nickname@users.noreply.github.com>` (more consistent with the practice of `Co-authored-by` tags).

**Comment by ejgallego** [comment]
Definitively having nickname to real name mapping is IMHO worth having.

Not sure about the commit tag message, we are already using `Reviewed-by` and `Acked-by` , `Signed-off` I think doesn't fit this use case, so maybe we could use non-standard `Merged-by` or `Accepted-by` ?

**Comment by SkySkimmer** [comment]
It's on the merge commit so Co-authored-by makes sense imo.
It would make github show the coqbot icon and the merger icon.

**Comment by ejgallego** [comment]
> It's on the merge commit so Co-authored-by makes sense imo.
> It would make github show the coqbot icon and the merger icon.

Oh, good idea!
