### ISSUE TITLE
Feature: check PRs for merge conflicts

### ISSUE THREAD

**Issue by SkySkimmer** [coq/bot#14]
Maybe on a timer rather than every merge.

**Comment by Zimmi48** [comment]
The bot runs `git` already to be able to push to GitLab so we could indeed check locally for the conflicts, but this would require pulling all PRs, so it seems more sensible to use the info already computed by GitHub...

**Comment by ejgallego** [comment]
One further advantage of having a queue is that newer jobs can cancel / override older ones.

[by the way, such kind of queue is what's needed for asyncronous proof processing :D]

**Comment by Zimmi48** [comment]
An async queue would be something like what is provided by https://github.com/c-cube/lwt-pipe?

**Comment by ejgallego** [comment]
> An async queue would be something like what is provided by https://github.com/c-cube/lwt-pipe?

Indeed, I think so !

**Comment by Zimmi48** [comment]
In the end, this was implemented by using an external Action.
