### ISSUE TITLE
coqbot should be able to resume CI minimization

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#143]
I'd like to be able to write things like

    @coqbot resume ci minimization ci-hott with
    ```
    some coq file here
    ```

And have minimization resume on the given file.  This would be useful at, for example, https://github.com/coq/coq/pull/13269#issuecomment-854117817, where minimization times out.  Most of the work to be done here is on my side on https://github.com/coq-community/run-coq-bug-minimizer; the only thing to do on the coqbot side is to recognize this sort of request and initiate CI minimization with an extra file of an appropriate name for the minimizer runner to recognize it.

**Comment by Zimmi48** [comment]
What is the extra file for? To allow the user to do part of the minimization work? And what about having the bot auto-trigger the new minimization as long as the minimizer has stopped because of a timeout?

**Comment by JasonGross** [comment]
The minimizer is re-entrant in the sense that it saves its partial progress in a file at many points, and if you kill the minimizer at any point and restart it running from the file that was saved, there's almost no difference.  (I'm going to have to add a flag that tells it to ignore the `coq-prog-args` header, because the header it records only knows about the version of Coq that's supposed to fail on the file, not both versions.  But this is a minor change and in fact should be unconditionally passed during CI minimization, because the invocation of Coq is read off the build log.)  So when the minimizer times out, it reports the intermediate file as the minimized file (and it is, it's just not minimized as much as the minimizer would like).

So the extra file is to record the state of minimization at the previous timeout, so that the minimizer can resume from there.  (Incidentally, the user could use this feature to do additional minimization, or to ask the minimizer to minimize something in the context of the PR.  I'm not sure how useful this is, since they won't get interactive feedback about their edits and whether or not they compile in the context of the PR, but it might end up being useful.)  Having the bot auto-trigger the new minimization would also be pretty easy; we'd just have to add a different endpoint and I could have the minimizer send a different curl request on timeout, so that minimization gets re-triggered.

**Comment by JasonGross** [comment]
@Zimmi48 I've implemented everything necessary on the minimizer side, I believe only changes on the coqbot side are needed to resume minimization.  In particular, sticking Coq code in `bug.v` will result in minimization resuming from that file.  Additionally, if the bot sticks a URL in the file `coqbot.resume-minimization-url`, in addition to asking the bot to post a comment on GitHub at the normal URL, the minimizer-runner will also use this URL to ask the bot to resume minimization.  In this case, the bot should stick the docker image in `coqbot.docker-image` (in addition to `.github/workflows/main.yml`), and should expect a reply at the URL in `coqbot.resume-minimization-url` with the following lines:
1. `cat coqbot-request-stamp`
2. the commit message with newlines replaced by `\t` (useful for making a new informative commit message) (generated by `echo -n "$(git log -1 --pretty=%B)" | tr '\n' '\t'`)
3. `cat coqbot.docker-image`
4. `cat coqbot.ci-target`
5. `cat coqbot.compiler`
6. `cat coqbot.failing-artifact-urls`
7. `cat coqbot.passing-artifact-urls`
8. `cat coqbot.failing-sha`
9. `cat coqbot.passing-sha`

After this (lines 10 and beyond) are the partially minimized file, which should be placed in `bug.v` to resume minimization.

Note that we currently unconditionally comment with the partially minimized file on GitHub, but we might want to change this in the future?

**Comment by JasonGross** [comment]
@Zimmi48 Do you have the time / inclination to implement the coqbot side of this?

**Comment by Zimmi48** [comment]
Yes, I'll try to look at this in the next few days.
