### ISSUE TITLE
Feature: comment with rendered doc

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#15]
It'd be nice to have coqbot comment with either a diff of the html output of the doc, or with the rendered version of any sections that change.  Presumably the former is easier; it could download the doc from whatever artifacts have them, and comment with the diff.

Ideally, it should comment only if there is a change to anything in the `doc/` folder, and it should update its existing comment (if it exists) whenever a push is made to the PR / whenever the doc pipeline completes.

**Comment by JasonGross** [comment]
As a first approximation, it'd be nice to have coqbot auto-post a link to the documentation artifact if there is a change in `doc/` (and to keep it updated whenever the PR changes).  (Or even just have one of the status updates include a link to the rendered doc, or have it show up under checks, or something.)

**Comment by Zimmi48** [comment]
Yes, I'll go for the first approximation of pushing a link in every case in the status check section.

**Comment by Zimmi48** [comment]
In addition to posting a direct link in the status section at the bottom of every PR, should we also link prominently to these artifacts from the main GitLab pipeline check in the "Checks" tab?

**Comment by Zimmi48** [comment]
For now, this feature seems sufficient as is. Let me know if you have suggestions of improvements.

**Comment by JasonGross** [comment]
It might be nice to have links directly to the rendered doc for each file that is changed by the PR.  This is minor, though, and the current setup is quite good

**Comment by Zimmi48** [comment]
Good idea! It's also reasonable to implement I think.

**Comment by Zimmi48** [comment]
Actually, let's turn this into a new issue.
