### ISSUE TITLE
coqbot should be more lax about closing draft PRs

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#161]
Draft PRs are easy to filter out and I think don't need to be closed after being labeled stale.

**Comment by SkySkimmer** [comment]
How do you filter draft prs?

**Comment by Zimmi48** [comment]
> How do you filter draft prs?

`-is:draft`

**Comment by Zimmi48** [comment]
> Draft PRs are easy to filter out and I think don't need to be closed after being labeled stale.

Please raise this question in a Coq Call. This was already discussed once before being implemented and, at the time, it was explicitly argued (by @ppedrot) that draft PRs should not be excluded from the mechanism.

**Comment by Zimmi48** [comment]
I'm closing this issue because it is a policy discussion to hold in a Coq Call or similar.
