### ISSUE TITLE
coqbot minimization should support an alternate mode that also inlines the standard library

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#177]
This consists of passing the extra flag `--inline-coqlib`.  I think we don't want to pass it by default because it might make the example much longer, but it's useful for making short cases like https://github.com/coq/coq/pull/14727#issuecomment-957082119 even more standalone.  The way to do it technically is probably too add an extra file that will contain extra arguments to the minimizer, one per line.  Not sure what the request should be called user-side.  "coqbot ci aggressive minimize"?

**Comment by JasonGross** [comment]
I've set up the minimizer to accept arguments from a file `coqbot.extra-args`.

**Comment by Zimmi48** [comment]
What about proposing this choice to the user only after coqbot answered with a first minimization result?

**Comment by Zimmi48** [comment]
Fixed by supporting `extra-arg=--inline-prelude` in `@coqbot minimize`, `@coqbot ci minimize` and `@coqbot resume ci minimize` calls (see https://github.com/coq/coq/wiki/Coqbot-minimize-feature).
