### ISSUE TITLE
Don't post minimization instructions when all failures are the same as master

### ISSUE THREAD

**Issue by SkySkimmer** [coq/bot#181]
eg https://github.com/coq/coq/pull/15198#issuecomment-975637479

**Comment by Zimmi48** [comment]
Alternative to #174. In #174, I assumed that this message is still useful to help contributors understand the cause of the failure. On the other hand, comments are a bit heavy in this case. Maybe just updating the GitHub Checks info to inform that the failure also currently happens in `master` would be helpful enough?
