### ISSUE TITLE
Expiration may be too far in the future for github

### ISSUE THREAD

**Issue by mattiasdrp** [coq/bot#204]
https://github.com/coq/bot/blob/15a4b50d576904f5d1643ce761b85133700ecbae/bot-components/GitHub_app.ml#L21-L27 

Specifically `(issuedAt + (60 * 10))`

Since this is computed based on `Unix.time`, if your computer's date is a bit too far in the future, GitHub will complain with the following json message:
```json
{"message":"'Expiration time' claim ('exp') is too far in the future","documentation_url":"https://docs.github.com/rest"}
```

Since you're only using the tokens for 40 minutes, maybe decrease the exp value to `issuedAt + (55 * 10)` for example?

**Comment by Zimmi48** [comment]
Sure, that sounds like a good change to make (feel free to create a PR with this change).
