### ISSUE TITLE
Improvement suggestions for the bench report.

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#218]
I agree that the main table is more compact in plain text that it could ever be in Markdown format. But for the top 25 speedups / slowdowns, there would be a big advantage to use Markdown: the FILE column could be used to provide clickable links (such as to: https://coq.gitlab.io/-/coq/-/jobs/2239434488/artifacts/_bench/html/coq-mathcomp-fingroup/mathcomp/fingroup/gproduct.v.html).

Furthermore, since the user time speedup / slowdown is also what most people are interested in, extracting just this information as a Markdown table and including it in the summary could also make sense.

(from https://coq.zulipchat.com/#narrow/stream/243318-coqbot-devs-.26-users/topic/bench.20report)

**Comment by Alizter** [comment]
Note to self or others:

https://github.com/coq/coq/blob/0e55aab52480bf6de6eabb6756aba379ba0a0653/dev/bench/render_line_results.ml#L74

Would need to be changed to additionally output a table in markdown format. This should be relatively simple to do.

Clickable links can be handled by coqbot quite easily as only a prefix is needed to turn those files into urls.

**Comment by Zimmi48** [comment]
The prefix should be `https://coq.gitlab.io/-/coq/-/jobs/<build_id>/artifacts/_bench/html/`.

**Comment by SkySkimmer** [comment]
Done in https://github.com/coq/coq/pull/17559
