### ISSUE TITLE
Support other projects that want to push PRs to GitLab

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#23]
GitLab CI is a great CI platform that can be used for GitHub projects too (thanks to CI/CD-only project mirroring). The only thing that is lacking is building pull requests (it only mirrors branch). In Coq, we use the present bot to push all new or updated PRs to branches that are named `pr-<number>` to GitLab (and we deleted them when the corresponding PR is closed). This is enough to have CI run for PRs (GitLab takes care of reporting back the status of the build). Other projects could be interested to use this capability as well. How to support them?

- The first solution is to support them on a case by case basis by having the bot listen to webhooks from other repositories and pushing to other repositories. This is easy to do in practice.
- The second solution is to provide a library of reusable GitHub / GitLab bot components with enough documentation so that other projects can easily have their own bot up and running (this is the plan).
- The third solution is to provide a "GitHub action" whenever these get actually released to all projects: https://github.com/features/actions. This could be set up more easily, with personalized workflows and does not require deploying on Heroku.

**Comment by Zimmi48** [comment]
Note that the first solution is already in place for opam-coq-archive.

**Comment by Zimmi48** [comment]
There is an issue to fix about the status reporting though (see coq/opam-coq-archive#535).

**Comment by Zimmi48** [comment]
> I wasn't aware of this service (still in beta indeed): https://github.com/features/actions

For now, GitHub actions only support the push events on public repositories, so they cannot be used yet. Let's wait and see.

> Is "GitLab's own GitHub integration" the same thing as GitLab's mirroring configuration of a GitHub repo? If yes, do you mean that with the latest version of coq/bot, the current  mirroring configuration of GitLab should be disabled for math-comp?

No. GitLab's support for GitHub is two-fold:
- Mirroring capability. (In particular, the CI/CD-only setup mirrors branches even in case of force-pushing to said branches, which wasn't the case with mirroring before.) @coqbot doesn't take care of this since GitLab does it well.
- Ability to push a status to GitHub (example: https://github.com/math-comp/math-comp/commits/11c1489d8906ef62485b9b9d145f44acc4b9471a). This status will be pushed for the commit that was built on GitLab CI. But in #25, it was requested that @coqbot supports merging with the base branch as is done in Travis. In this case, GitLab CI won't report the status check for the right commit. This is why on the main Coq repository, this integration has been disabled and is handled instead by @coqbot. This part needs to be generalized to handle pushing status checks to other repositories.

**Comment by erikmd** [comment]
Actually I've just seen this has already be suggested by @gares, cf. https://github.com/coq/bot/issues/25#issuecomment-441389593

**Comment by erikmd** [comment]
Indeed! Thanks @Zimmi48

**Comment by Zimmi48** [comment]
@erikmd The aforementioned issue is fixed and the setup to use @coqbot is now documented in https://github.com/coq/bot#rely-on-coqbot-to-synchronize-your-github-prs-with-your-gitlab-project.

**Comment by erikmd** [comment]
@Zimmi48 ok, great :+1:

@CohenCyril could you look after this configuration after merging math-comp/math-comp#266?

**Comment by erikmd** [comment]
Hi @Zimmi48, I have only one question: you suggest to disable GitLab's own status check reporting feature (by going to the "Settings" / "Integration" menu) but maybe this will prevent GitLab from reporting the build status of branches builds, e.g. for master?

**Comment by Zimmi48** [comment]
No, @coqbot will report back all build status without making a distinction whether it came from a PR or from a branch.

**Comment by Zimmi48** [comment]
For now, I'll close this issue, even if it would make sense to implement the second or third points mentioned in the initial description.
