### ISSUE TITLE
Minimizer is treating all code blocks as Coq

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#269]
See https://github.com/coq/coq/issues/17252#issuecomment-1426793683

Relevant code: https://github.com/coq/bot/blob/3deea7d3c044371cf5df92ae70a51ec4339071f8/src/actions.ml#L1931-L1940
and https://github.com/coq/bot/blob/3deea7d3c044371cf5df92ae70a51ec4339071f8/src/bot.ml#L67-L103

**Comment by JasonGross** [comment]
Maybe related: #268

**Comment by JasonGross** [comment]
Current leading hypothesis is that GitHub is reporting the comment as containing ` ```shell ` rather than what the user actually wrote.

**Comment by Zimmi48** [comment]
Was this fixed by #270?

**Comment by JasonGross** [comment]
#270 failed to fix this, but #274 should have actually fixed this.  I'll reopen if it's still an issue
