### ISSUE TITLE
Auto resumption for non-ci-minimization

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#272]
Ah, no, we unfortunately haven't set up autoresumption for non-ci-minimization yet.  It's a bit trickier in this case, since we need to transmit not just the new file and some parameters, but also the initial script.

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/17252#issuecomment-1440693777_

**Comment by Zimmi48** [comment]
Duplicate of #197
