### ISSUE TITLE
Migrating the backporting tracking mechanism to Projects V2.

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#278]
In https://github.com/orgs/coq/projects/8 (private and only visible to core devs and bot maintainers for now, to avoid polluting most users with this experiment), I have experimented with a backporting tracking project using the new GitHub Projects.

One advantage that I can see is that instead of creating a new project for each new release branch, we could use a single project with views per release branches (I have separated one view for "Request inclusion in ..." and one view for "Shipped in ...").

The idea of the workflow would be the following:
- When a pull request is merged, coqbot looks at its milestone. If the milestone's description contains a request to backport to one (or several) release branch(es), then coqbot will:
  1. Add the pull request to this project (always the same) and retrieve the item ID.
  2. Search for existing single-select fields in the project named "vX.X status" for each VX.X branch to which backporting was requested.
  3. Retrieve the fields' ID and the IDs of their values if they exist, create them if they don't exist yet (always with the same two values "Request inclusion" and "Shipped", with the same colors and the same descriptions).
  4. In the case where the fields are created, also create new views in the project.
  5. Set the value of these fields to "Request inclusion" or "Shipped" for the newly added item depending on whether the pull request was merged in `master` or in the release branch.
- When a pull request is backported to a release branch, coqbot looks for the field in the project corresponding to the release branch and sets the value of this field to "Shipped".

Currently, there is a limit at 1200 non-archived items in a GitHub project, which means that from time to time we might need to archive items corresponding to old releases and delete the corresponding views.

**Comment by SkySkimmer** [comment]
So this would use a common project for all releases?

**Comment by Zimmi48** [comment]
GraphQL request for point (ii):

```graphql
query {
  organization(login: "coq") {
    projectV2(number: 8) {
      field(name: "v8.16 status") {
        ... on ProjectV2SingleSelectField {
          id
          name
          options(names: ["Request inclusion", "Shipped"]) {
            id
            name
            color
          }
        }
      }
    }
  }
}
```

returns:

```json
{
  "data": {
    "organization": {
      "projectV2": {
        "field": {
          "id": "PVTSSF_lADOAAl6js4APDhezgJnVrQ",
          "name": "v8.16 status",
          "options": [
            {
              "id": "c4602a9f",
              "name": "Request inclusion",
              "color": "GREEN"
            },
            {
              "id": "8ba5f62a",
              "name": "Shipped",
              "color": "PURPLE"
            }
          ]
        }
      }
    }
  }
}
```

**Comment by Zimmi48** [comment]
GraphQL request for step (i):

```graphql
  mutation addCard($card_id:ID!, $project_id: ID!) {
    addProjectV2ItemById(input:{contentId:$card_id,projectId:$project_id}) {
      item {
        id
      }
    }
  }
```

This requires knowing the project ID, which is something else that we could get from the previous query, by modifying it slightly. (Thus, we should reverse step (i) and (ii).)

**Comment by Zimmi48** [comment]
GraphQL request for step (v) and also second bullet point:

```
  mutation addCard($card_id:ID!, $project_id: ID!, $field_id: ID!, $field_value: String!) {
    updateProjectV2ItemFieldValue(input: {projectId: $project_id, itemId: $card_id, fieldId: $field_id, value: {singleSelectOptionId: $field_value}}) {
      clientMutationId
    }
  }
```
