### ISSUE TITLE
Incorrect link to gitlab pipeline in github check

### ISSUE THREAD

**Issue by SkySkimmer** [coq/bot#282]
https://github.com/coq/coq/pull/17368/checks?check_run_id=13553547137 links to https://gitlab.com/coq/coq/pipelines/870446560 but this is a 404
The correct link is https://gitlab.com/coq/coq/-/pipelines/870446560 (with a `/-/`)

I guess the non-`/-/` link stopped working recently.

**Comment by SkySkimmer** [comment]
(the individual job links seem fine and have a `/-/`)

**Comment by Zimmi48** [comment]
Thanks for the report! I'm fixing this as part of #276 because that part of the code has changed in this PR.
