### ISSUE TITLE
ci minimization is broken due to change in format of reporting results

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#290]
Did the CI recently stop reporting on job configuration information?
![image](https://github.com/coq/bot/assets/396076/87238f36-cb3f-402c-9884-60fbd69c51a9)
https://github.com/coq/coq/pull/17937/checks?check_run_id=16164573704

Compare with
https://github.com/coq/coq/pull/17811/checks?check_run_id=14777475244
![image](https://github.com/coq/bot/assets/396076/b3a0035a-16a3-475c-b746-66006e4c7880)

-------

I was unable to minimize any of the CI targets that you requested.
library:ci-fiat_crypto could not be minimized (Could not find needed parameters for job library:ci-fiat_crypto in summary:
<details><summary>Summary</summary>

This job has failed. If you need to, you can restart it directly in the GitHub interface using the "Re-run" button.

We show below an excerpt from the trace from GitLab starting around the last detected "Error" (the complete trace is available [here](https://gitlab.com/coq/coq/-/jobs/4935724610)).
</details>

)

_Originally posted by @coqbot-app[bot] in https://github.com/coq/coq/issues/17937#issuecomment-1692293340_

**Comment by Zimmi48** [comment]
Looking at the code constructing the missing message, it parses the trace of the job to find the information it needs, and it prints the missing line only if it finds it all, so as soon as some information is missing, none is printed:

https://github.com/coq/bot/blob/7c4fbb627691f74a61f946e71a90e3c69aa79775/src/actions.ml#L74-L130

**Comment by Zimmi48** [comment]
I have one very likely candidate responsible for breaking this trace parsing: https://github.com/coq/coq/pull/17785

**Comment by Zimmi48** [comment]
Indeed, this PR removed the `OPAM_SWITCH` and the `COMPILER_EDGE` variables. So not just the parsing will need to be adapted, but also the run-bug-minimizer scripts.

Now the script should always use: `"${COMPILER}${OPAM_VARIANT}"`. See https://github.com/coq/coq/commit/607252748f96914b940668730d829d2d55be1949#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7L53-L56.

**Comment by Zimmi48** [comment]
I believe this issue to be entirely resolved, but this will need to be confirmed in the next minimization attempts. At least, the reporting of where jobs ran is back to normal.
