### ISSUE TITLE
Automatically run opam-publish.

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#30]
The bot could listen to branch / tag creation webhooks. When a new tag is created in a repository which contains an `opam` file, it could run `opam-publish` to update the corresponding package on opam-coq-archive. Webhooks can be installed on individual repositories or organization-wide, so it should be very easy to support all repositories in an organization such as coq-community (or coq-contribs if the repositories contained `opam` files). Upon PR creation, the bot would ping the tag creator (and possibly also all listed maintainers if the repository contain a `meta.yml` with this information) to check the PR.

Note that I have never used `opam-publish` so I might be a little naive about it.

Initially proposed in https://github.com/coq/opam-coq-archive/pull/500#issuecomment-452257246.

**Comment by ejgallego** [comment]
Shouldn't `opam-publish` be instead called by the deploy phase of the corresponding CI?

**Comment by Zimmi48** [comment]
>Shouldn't opam-publish be instead called by the deploy phase of the corresponding CI?

Hum, that sounds right indeed.

**Comment by Zimmi48** [comment]
Closing in favor of https://github.com/coq-community/manifesto/issues/49
