### ISSUE TITLE
Use a more descriptive title in merge commits

### ISSUE THREAD

**Issue by ejgallego** [coq/bot#43]
As of today, the bot will merge PRs for the CI with a commit message such as:
```
Bot merge 28ea4994 into 84b27155
```
which makes hard to know which is the PR the merge is referring to. I'd be great instead if the bot would add the PR title to the merge commit:
```
Bot merge 28ea4994 into 84b27155: "Add missing zify class instances"

**Comment by SkySkimmer** [comment]
TBH the commit hashes are not especially useful since they're already in the metadata, maybe we should do something like `[CI merge] PR coq/coq#10998: Add missing zify class instances`

**Comment by ejgallego** [comment]
Thanks @jtcoolen !
