### ISSUE TITLE
Autoposting documentation links

### ISSUE THREAD

**Issue by JasonGross** [coq/bot#50]
It'd be really cool if coqbot could post a link to the CI-generated documentation for PRs that touch any of the doc files (at least whenever the doc job succeeds).  Bonus points if the link(s) point exactly to the pages that were changed in the PR.  I found myself wanting this at https://github.com/coq/coq/pull/12129#issuecomment-619415060

**Comment by Zimmi48** [comment]
@JasonGross That's a duplicate of your own request (#15) and that's already mostly solved: the link to the CI-generated documentation is not posted in a comment but is in the status checks:

![2020-04-25-222924_672x287_scrot](https://user-images.githubusercontent.com/1108325/80290267-8bba7500-8744-11ea-991f-187ba0e6187b.png)

**Comment by JasonGross** [comment]
Ah, neat!
