### ISSUE TITLE
Could coqbot help to enhance GitLab CI integration in GitHub "Checks" tab?

### ISSUE THREAD

**Issue by erikmd** [coq/bot#54]
With coqbot the GitHub / GitLab CI integration in PRs is very fine!

But I've just noticed that some GitHub feature was not handled though, the `Checks` tab is currently empty: https://github.com/math-comp/math-comp/pull/524/checks (see screenshot below).

<details><summary>Screenshot</summary>

![2020-06-07_23-40-51_Screenshot_GitHub+GitLab_CI_Checks_empty](https://user-images.githubusercontent.com/10367254/83980841-2a77eb00-a919-11ea-8f29-bcd82256ca07.png)

</details>

to be compared with e.g. [that of `Travis CI`](https://github.com/erikmd/docker-coq-travis-ci-demo-1/pull/1/checks),

or [that of `GitHub Actions`](https://github.com/erikmd/docker-coq-github-action-demo/pull/5/checks).

Of course:
* this feature suggestion is not crucial at all
* maybe this should/could be handled by GitLab CI itself

but if GitLab doesn't plan to implement this (which has to be handled by a dedicated GitHub app? or maybe via an API call, I didn't have a look), coqbot might help at some point? (provided it is easy to implement this with the current architecture)

**Comment by Zimmi48** [comment]
For future reference, if we want to create checks using the GraphQL API, we'll need to use the `createCheckRun` and `createCheckSuite` mutations (documented at https://docs.github.com/en/graphql/reference/mutations#createcheckrun) and pass a special "Accept" header to get the `schema.json` which includes those (cf. https://docs.github.com/en/graphql/overview/schema-previews#checks-preview).

**Comment by Zimmi48** [comment]
FYI this is now implemented, but it requires activating the GitHub App (and removing the manually configured GitHub-side webhook to avoid duplicating the requests). Furthermore, the only advantage as of today is that the checks are listed in the "Checks" tab and that allow failure jobs are reported as "neutral". But I'm looking for feedback for what additional info to put in the GitHub Checks tab.

**Comment by Zimmi48** [comment]
Let's use #109 for the feedback on this feature.

**Comment by erikmd** [comment]
Thanks @Zimmi48 (I've just realized I should have put [my feedback](https://github.com/coq/bot/issues/109#issuecomment-728848400) in this issue #54, sorry :disappointed:)
