### ISSUE TITLE
Print commit hash in allow_failure notification

### ISSUE THREAD

**Issue by SkySkimmer** [coq/bot#63]
I think this would be nice. It would look like "FYI job [test-suite:4.12+trunk+dune](https://gitlab.com/coq/coq/-/jobs/618250406) has failed for commit https://github.com/coq/coq/commit/1109f3d55a8d2c76b05a7aa85034f02c71253cbd" (we can just print the short hash and github should linkify it)

Maybe also print the 1st line of the commit message

**Comment by Zimmi48** [comment]
Sorry for missing this issue: last week was very busy.

I agree with your suggestion. If it's only about the commit hash, it should be pretty easy to implement given that the commit hash info is already present in the context where the message is built:

https://github.com/coq/bot/blob/f9ce5a99ba5fa3a32370d2b64ac28848a11cfdda/bot.ml#L361-L369

>we can just print the short hash and github should linkify it

Or the full hash: GitHub will display it the same.

If we want to add the 1st line of the commit message as well, it would require some more changes (to get back this info from the query to get information on the PR) but it should still be reasonably easy.
