### ISSUE TITLE
Coqbot webhooks failing for me

### ISSUE THREAD

**Issue by connorshea** [coq/bot#96]
Two PRs opened today aren't displaying the checks correctly 🤔 https://github.com/connorshea/vglist/pull/1466 and https://github.com/connorshea/vglist/pull/1465

They were working just yesterday, fwiw. I tried closing the PRs and reopening them but that didn't do anything to make the checks go through.

I haven't changed any configurations in either GitHub or GitLab and I looked at the audit logs for GitLab, nothing there that seems suspect. It actually synced the branch to GitLab just fine.

It looks like the webhook for `https://coqbot.herokuapp.com/github` is failing in my GitHub repo, returning a 500 error.

I can provide the full payload body if you need that, but I'd rather not put that into this issue since I assume it has private information in it :)

For example, the webhook call with ID ` ba714800-e744-11ea-9e34-0d30c62b0186` failed at Wed, 26 Aug 2020 02:34:57 GMT (or the hook was called then?).

**Comment by Zimmi48** [comment]
Thanks for the report! We have identified the problem and we are going to fix it shortly.

**Comment by Zimmi48** [comment]
We've merged the fix. The deploy job is running (https://github.com/coq/bot/runs/1030981576) and should be over in 10 minutes or so. After that, you can try to redeliver the failing webhooks or else reclose / reopen the PRs.

**Comment by connorshea** [comment]
Thanks!
