### ISSUE TITLE
PR not pushed on GitLab

### ISSUE THREAD

**Issue by Zimmi48** [coq/bot#98]
PR coq/coq#12894 is not getting pushed on GitLab. The webhook is correctly received but it results in:

```
From https://github.com/silene/coq
  * [new branch]            closure_tag            -> head-closure_tag-e375260a82022eab63241ebd5ef13d4ae0c4b7ab
  * [new tag]               last-coqide-for-8.4pl3 -> last-coqide-for-8.4pl3
 /bin/sh: syntax error: unexpected "("
```

I retried the webhook and it resulted in the same error.
This is especially strange because in the meantime other PRs have been pushed to GitLab without an issue.

**Comment by SkySkimmer** [comment]
I guess because the PR title has a parenthesis

**Comment by Zimmi48** [comment]
Thanks, indeed, I just guessed the same thing.

**Comment by Zimmi48** [comment]
Would a patch like this fix the issue?

```diff
diff --git a/make_ancestor.sh b/make_ancestor.sh
index 420f97a..2df553e 100755
--- a/make_ancestor.sh
+++ b/make_ancestor.sh
@@ -12,7 +12,7 @@ if [ $# != 4 ]; then >&2 echo Bad argument count; fi
 
 base=$1
 head=$2
-pr_title=$3
+pr_title="$3"
 prnum=$4
 
 basecommit=$(git rev-parse "$base")
```

**Comment by SkySkimmer** [comment]
The error mentioning parens is because the PR title has them, but the error is because the PR title has a single quote which breaks the quoting in `f "./make_ancestor.sh %s %s '%s' %d" base head pr_title pr_number`
Why do we go through the shell here instead of creating the process directly?

**Comment by Zimmi48** [comment]
>  Why do we go through the shell here instead of creating the process directly?

No particular reason. How do you do that?
